// <auto-generated />
using System;
using CarritoCompras.Api.Compartidos.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarritoCompras.Api.compartidos.Persistencia.Migraciones
{
    [DbContext(typeof(CarritoDbContext))]
    [Migration("20250127033746_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CarritoCompras.Api.Compartidos.Domain.Entidades.Carrito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_por");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT")
                        .HasColumnName("modificado_por");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_carrito_compras");

                    b.ToTable("carrito_compras", (string)null);
                });

            modelBuilder.Entity("CarritoCompras.Api.Compartidos.Domain.Entidades.Elemento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<Guid>("CarritoId")
                        .HasColumnType("TEXT")
                        .HasColumnName("carrito_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("creado_por");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("TEXT")
                        .HasColumnName("modificado_por");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT")
                        .HasColumnName("precio");

                    b.Property<string>("UrlImagen")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url_imagen");

                    b.HasKey("Id")
                        .HasName("pk_elementos");

                    b.HasIndex("CarritoId")
                        .HasDatabaseName("ix_elementos_carrito_id");

                    b.ToTable("elementos", (string)null);
                });

            modelBuilder.Entity("CarritoCompras.Api.Compartidos.Domain.Entidades.Elemento", b =>
                {
                    b.HasOne("CarritoCompras.Api.Compartidos.Domain.Entidades.Carrito", "Carrito")
                        .WithMany("Elementos")
                        .HasForeignKey("CarritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_elementos_carritos_carrito_id");

                    b.Navigation("Carrito");
                });

            modelBuilder.Entity("CarritoCompras.Api.Compartidos.Domain.Entidades.Carrito", b =>
                {
                    b.Navigation("Elementos");
                });
#pragma warning restore 612, 618
        }
    }
}
